### ISSUE TITLE
This project needs Unit Testing

### ISSUE THREAD

**Issue by gir489** [lolp1/Process.NET#10]
I find as I write more and more code and expand the project, the greater the need becomes for Unit testing.

Has the project contributors already decided on a unit testing framework? Would it be OK if I added one?

I think we'd need to write an external C++ program that its only purpose is to be attacked by Process.NET. IE: we have like a CrackMe that has to be solved by Process.NET and the Unit Tests assert that the CrackMe has been cracked. Ideally, we'd want to test both an external and local test, and 32-bit and 64-bit tests. I see there's an issue currently opened about Process.NET not working in 32-bit, which I have myself confirmed does not work. So we'd probably need to write an internal asset to the test that just declares byte arrays, and see if we can manipulate it with signature catching. [Maybe we could also implement something similar to this project](https://github.com/learn-more/findpattern-bench), where we could benchmark different methods of pattern scanning? The LINQ method "works", but I'd much prefer to see a [Boyer–Moore–Horspool](https://en.wikipedia.org/wiki/Boyer%E2%80%93Moore%E2%80%93Horspool_algorithm) implementation.

I have used [NUnit](https://www.nunit.org/) myself professionally, but only to do very minor things. I've been a Java developer most of my career and wrote a lot more JUnits than NUnits. However, the concept is the same. Mock external interfaces, make sure code gets hit, expected results, etc etc.

Thoughts?

**Comment by gir489** [comment]
Here's a quick NUnit test I just wrote.

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Process.NET
{
    using NUnit.Framework;

    [TestFixture]
    class ProcessDotNetTest
    {
        [Test]
        public void TestSignature()
        {
            var process = new ProcessSharp(System.Diagnostics.Process.GetCurrentProcess(), Memory.MemoryType.Local);
            Assert.IsTrue(process.Memory.GetType() == typeof(Memory.LocalProcessMemory));
        }
    }
}`

**Comment by lolp1** [comment]
@gir489 Sadly, the contribution has been only me. I've wanted to finish the features I want but have not had time, getting some motivation though :).

To answer your question though, no, no unit test have been added. However, this project is based on ZenLulz's MemorySharp, which does have a really good set of integration tests. It should not be too hard to piece together valid test for Process.NET baed off his existing test.

Process.NET is simply a more modular MemorySharp with in-process / x64 support and some extra features like input/message hooks.

https://github.com/ZenLulz/MemorySharp/tree/master/test/IntegrationTests is his test. I welcome any unit testing pull request, in fact part of lack of motivation comes from the lack of test.

**Comment by gir489** [comment]
So after a nice round of testing the 32-bit code with NUnit, I discovered that NUnit doesn't play nice with 64-bit. As soon as you turn on 64-bit compile mode, all your tests vanish and you can't run them with the NUnit Runner anymore, [which is a long standing issue](https://github.com/nunit/nunit-vs-adapter/issues/16) that I guess the NUnit team refuses to fix.

**Comment by lolp1** [comment]
@gir489 

I'd like to try and replicate the intergration test from memorysharp by zenlulz in near future :)

**Comment by Akaion** [comment]
I'm happy to write a set of unit tests for this project @lolp1. 

Maybe you could provide me with a means of communicating with you so we can collaborate properly?

**Comment by lolp1** [comment]
Going to close this for now.
