### ISSUE TITLE
Issue readings patterns on x64

### ISSUE THREAD

**Issue by BalooDaCat** [lolp1/Process.NET#13]
Hello, thanks for a great library it's a real time saver.
There's an issues with reading patterns on x64 currently where the application will shutdown without throwing an error therefor I can't really give you more details on it but is it something you could look into?

**Comment by lolp1** [comment]
> 
> 
> Hello, thanks for a great library it's a real time saver.
> There's an issues with reading patterns on x64 currently where the application will shutdown without throwing an error therefor I can't really give you more details on it but is it something you could look into?

Can you give me the code example, or attach a debugger and step through, perhaps even just log a try catch?

**Comment by BalooDaCat** [comment]
Here's the issue

`try
            {
                AllocConsole();

                ProcessSharp = new ProcessSharp(System.Diagnostics.Process.GetProcessesByName("PathOfExile_x64").FirstOrDefault());
                ProcessSharp.Memory = new ExternalProcessMemory(ProcessSharp.Handle);

                do
                {
                    switch (Console.ReadLine())
                    {
                        case "title":
                            Console.WriteLine(ProcessSharp.WindowFactory.MainWindow.Title);
                            break;

                        case "info":
                            Console.WriteLine($"Base: {ProcessSharp.Native.MainModule.BaseAddress.ToInt32()}\n" +
                                              $"Module: {ProcessSharp.Native.MainModule.FileName}\n" +
                                              $"Base from Pattern: ");
                            break;

                        case "get":
                                var scanner = new PatternScanner(ProcessSharp.ModuleFactory.MainModule);
                                Console.WriteLine(scanner.Find(DataAddressPattern));
                            break;

                        case "quit":
                            Console.WriteLine("Shutting down");
                            Shutdown();
                            break;

                        case "test":
                            Console.WriteLine("Confirm");
                            break;
                    }
                    
                } while (Console.ReadLine() != "exit now");

            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
            
        }`

The following example is hosted in it's own appdomain from notepad and when attempting to scan it will exit without throwing an exception

**Comment by lolp1** [comment]
@BalooDaCat 
> The following example is hosted in it's own appdomain from notepad and when attempting to scan it will exit without throwing an exception

Since you're external you probably need to construct ProcessSharp differently, likely the cause here. Try it like this: 
```csharp
ProcessSharp = new ProcessSharp(System.Diagnostics.Process.GetProcessesByName("PathOfExile_x64").FirstOrDefault(), MemoryType.Remote);
```
Otherwise, you will not have an open handle unless you open it your self. Above opens it for you in the constructor if it is remote.

```csharp
($"Base: {ProcessSharp.Native.MainModule.BaseAddress.ToInt32()}\n" +
```
You are using path of exile x64 client, which is a x64 process, would this not cause an arhitmetic error? You should also make sure PatternScannerAlgorithm is set to PatternScannerAlgorithm.Naive if you were using the standard format to be sure as that's the one I wrote and tested in the examples.

**Comment by BalooDaCat** [comment]
Thanks, that makes a lot of sense it seems to be working now.
Some of the stuff in there was just left from testing things so ignore those, made the edit in a hurry. :)
