### ISSUE TITLE
WndProc Hook

### ISSUE THREAD

**Issue by caowenyu75** [lolp1/Process.NET#17]
Hi,

I tried the wndProc hook on Wow. But SetWindowLong only works on the process itself instead of an external process, is that right?

Thank you,

**Comment by lolp1** [comment]
> 
> 
> Hi,
> 
> I tried the wndProc hook on Wow. But SetWindowLong only works on the process itself instead of an external process, is that right?
> 
> Thank you,

That is right, you need direct memory access. You may also use assembly to hook it from a remote process.
