### ISSUE TITLE
Nuget support

### ISSUE THREAD

**Issue by FlyCrafting** [lolp1/Process.NET#19]
Last version on Nuget is 1.0.8 (04.12.2016) and its very outdated because there were commits in 2017-2018 years and few days ago. 
Can you pls upload the latest project version to the Nuget?

**Comment by lolp1** [comment]
> Last version on Nuget is 1.0.8 (04.12.2016) and its very outdated because there were commits in 2017-2018 years and few days ago.
> Can you pls upload the latest project version to the Nuget?

Yeah, I will update the package tomorrow evening :)
