### ISSUE TITLE
Keyboard & Mouse hook makes my mouse or keyboard so slow

### ISSUE THREAD

**Issue by FlyCrafting** [lolp1/Process.NET#20]
When I setup Keyboard or Mouse Hook and Enable it, my mouse (or keyboard) become super laggy, I can't move it at all and when I press keyboard keys it has huge delay (about 5-10 seconds).

I don't understand the main purpose of Keyboard and Mouse Hook but I think its not correct behavior.
I just wanted to subscribe to keyboard press.

UPD: It doesn't work in Console App but works in WPF app. I think you should add it to readme that it will work only in wpf / winforms apps.

**Comment by lolp1** [comment]
> When I setup Keyboard or Mouse Hook and Enable it, my mouse (or keyboard) become super laggy, I can't move it at all and when I press keyboard keys it has huge delay (about 5-10 seconds).
> 
> I don't understand the main purpose of Keyboard and Mouse Hook but I think its not correct behavior.
> I just wanted to subscribe to keyboard press.
> 
> UPD: It doesn't work in Console App but works in WPF app. I think you should add it to readme that it will work only in wpf / winforms apps.

Was not aware it did not work in a console app. I will make note of that. Thanks.
