### ISSUE TITLE
Namespace conflict? How to resolve

### ISSUE THREAD

**Issue by joonhwan** [lolp1/Process.NET#3]
Hi, due to this nice looking library's namespace is under wellknown "Process", compiler complains it cannot find Process namespace

```
error CS0246: The type or namespace name 'Process' could not be found (are you missing a using directive or an assembly reference?)
```

my code looks like...

``` c#
using Process.NET.Windows.Keyboard;

namespace AutoRcs.Remote.B9.App
{
    public class RxKeyHooker
    {
        private readonly KeyboardHook _keyboardHook;

        public event System.Action CloseRequested;

        public RxKeyHooker()
        // ...
```

Any hint?

Of course I already installed process.net from nuget and  process.net library is in the references node in solution explorer. 

Thanks in advance.

**Comment by lolp1** [comment]
Thanks for trying the library out first of all. Secondly, it is my first nuget package so it may have issues. However, I did just take a moment to download the nuget into a brand new application to test and all works fine.

The issue you are likely having is you are trying to access the System.Diagnostics.Process some where. Since there is an over-lap in this case, you would need to use the fully qualified name space. For example:
// would not work
var process = Process.GetCurrentProcess();
// should work
var process = System.Diagnostics.Process.GetCurrentProcess();

Here is the full sample code I just tested using the keyboard hook and seems to be fine. I am including it since it seems thats what you are after.

``` csharp
using System;
using System.Windows.Forms;
using Process.NET.Windows.Keyboard;

namespace WindowsFormsApplication1
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private KeyboardHook _keyboard;

        private void button1_Click(object sender, EventArgs e)
        {
            if (_keyboard != null)
            {
                return;
            }

            _keyboard = new KeyboardHook("Test");

            if (!_keyboard.IsEnabled)
            {
                _keyboard.Enable();
            }

            _keyboard.KeyDownEvent+= KeyDownEvent;
        }

        private void KeyDownEvent(KeyboardHookEventArgs keyboardHookEventArgs)
        {
            if(richTextBox1.InvokeRequired)
                richTextBox1.AppendText("Hi" + Environment.NewLine);
            else
            {
                richTextBox1.AppendText("Hi" + Environment.NewLine);
            }
        }
    }
}

```

**Comment by lolp1** [comment]
Responded on the open issue on Git. Let me know if that works for you. Thanks.

Date: Tue, 7 Jun 2016 00:32:36 -0700

**Comment by joonhwan** [comment]
Oh.. now I realized what was the problem after creating simplest winform code(I tried to use this library in my working project which has large build output message so could not catch it easily).

It was due to .net framework version that is being used for Process.NET you uploaded in nuget site.
I'm currently using VS 2013 on which .net 4.5.x is default. 

```
1>------ Build started: Project: ProcessDotNetTest, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3274: The primary reference "Process.NET, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.6.1" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".
1>c:\prj\test\ProcessDotNetTest\ProcessDotNetTest\MainForm.cs(2,7,2,14): error CS0246: The type or namespace name 'Process' could not be found (are you missing a using directive or an assembly reference?)
1>c:\prj\test\ProcessDotNetTest\ProcessDotNetTest\MainForm.cs(8,17,8,29): error CS0246: The type or namespace name 'KeyboardHook' could not be found (are you missing a using directive or an assembly reference?)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Does this mean that I cannot use this library in my .net environment?

**Comment by lolp1** [comment]
Good news, you can use it in your environment. I would suggest cloning the project, and changing the settings for the version do your 4.5.x and compiling. It has nothing to make it incompatible with those versions, I just tend to always use the latest version personally.

**Comment by joonhwan** [comment]
I forked/cloned/built. 
Added new project for net4.5.2 build and using it ok now. thanks.

**Comment by lolp1** [comment]
I'm glad you got it fixed. Perhaps it is worth while to make a 4.5.2 branch and to add that version to the nuget as we..
