### ISSUE TITLE
PatternScanner Win32(x86)

### ISSUE THREAD

**Issue by phengus** [lolp1/Process.NET#5]
Creating a simple Project with the basic scanner works with x64 builds, but in x86 builds throws Win32Exception cannot read X bytes from 0x00400000.

Throws exception when just initializing the scanner with 

var scanner = new PatternScanner( process.ModuleFactory.MainModule );

**Comment by lolp1** [comment]
Is "prefer 32 bit" checked in your x86 project build that causes this error?

**Comment by phengus** [comment]
I don't have that set. `Prefer 32 Bit` is not checked for sure. I have x86 builds to build x86 builds and x64 builds to build 64 bit builds. I was using Fasm.Net with it, but fasm.net uses x86(32 bit) only. Was planning to use pattern scanner with fasm.net.

To alleviate this issue, I made two project files. In "Any CPU", one builds the x64 build of process.net and uses that and another project to use the 32bit with fasm. The 64 bit scans and outputs the found address to a text file that the 32 bit project then uses and imports.

[Edit] That may have been the problem. Not sure what happen this time. But selecting x86 build ran fine this time. 

[Added] Started doing it again. Going to test if it's the dev environment or not. It's not a compiler error but a run time error. Compiles fine, but when ran, throws a win32 exception. Which i find weird.
