### ISSUE TITLE
Is there a reason to tightly couple to 4.6.1?

### ISSUE THREAD

**Issue by gir489** [lolp1/Process.NET#7]
I don't see a whole lot added between 4.5 and 4.6.1 to the .NET runtime that would be of relevance to this project. Any particular reason the NuGet project forces 4.6.1?

**Comment by lolp1** [comment]
The NuGet package is actually more up to date than the Github, mainly, it offers support for x64 detours and a couple bug fixes. I will rebuild the latest version and commit it tomorrow. Process.NET commits from now on at least will always just use the latest release framework, as it is intended to support modern systems running .NET.

**Comment by gir489** [comment]
There are also 2 projects on NuGet, which is quite confusing. Process.NET x64, which is on 1.0.0, and lacks quite a bit of features. And Process.NET which is on 1.0.8, and can compile just fine on x64. I recommend purging the x64 variant, as it just confuses people.

**Comment by lolp1** [comment]
Yeah x64 is just a waste and I need to remove it soon. I did not know how to use Nuget or github properly when I started this project clearly... haha

**Comment by alexis-** [comment]
Hi,

Process.NET is a godsend, exactly what I have been looking for. Any luck to see the commit pushed to GitHub ?
A *develop* branch would be fine if you feel it isn't ready for *master*.

Thank you !
Alexis

**Comment by lolp1** [comment]
I need to make a development branch and commit latest changes. Some time this week.

**Comment by alexis-** [comment]
Sounds good. Any ETA ?

**Comment by lolp1** [comment]
@alexis- 
https://cdn.discordapp.com/attachments/471929553388830740/471951341489618954/Process.NET.rar
this is a download to my latest version which supports x64 detours and such have not got around to touching the git side of things

**Comment by alexis-** [comment]
@lolp1 
Thank you, I will dig into it.

I have a fork of Process.NET (https://github.com/supermemo/Process.NET) with the following updates:
- Added Register Call Convention (Borland)
- Added Thread Hijacking
- Added ObjPtr (allows recursive pointers)
- Refactored Dword Patterns
- Added Dword Call Pattern (extract call address from signature)
- Updated to Unsafe casting (based on https://blog.aevitas.co.uk/extremely-fast-memory-manipulation/)
- Minor other additions

I understand this is an older project of yours and that you have more pressing concerns.
Would these changes warrant your time/attention for a PR ?

Cheers,
Alex
