### ISSUE TITLE
Process.NET NuGet wants to pack Process.NET.xml in to the PE

### ISSUE THREAD

**Issue by gir489** [lolp1/Process.NET#8]
For some reason, Process.NET keeps wanting to add Process.NET.xml to my binary. If I open up the XML, it looks like some kind of parsed-out documentation for the project. Why does this need to be in my binary?

**Comment by lolp1** [comment]
I honestly have no clue, I am guessing it is for intellisense or something? I did not specifically try and have it do that but I can remove it next commit/nuget push tomorrow if its an issue.

**Comment by gir489** [comment]
I was just wondering why it was there.

**Comment by lolp1** [comment]
I will look into it and let you know here when I find out my self tomorrow ^^

**Comment by lolp1** [comment]
Going to be updating the NuGet and stuff shortly. I will close this for now and re-open at a later time this week if I run into issues.
