### ISSUE TITLE
Project fails to compile with Visual Studio 2013

### ISSUE THREAD

**Issue by gir489** [lolp1/Process.NET#9]
http://D/Coding/Process.NET/src/Process.NET/Threads/FrozenThread.cs(38,20,38,21) : error CS1056: Unexpected character '$'
http://D/Coding/Process.NET/src/Process.NET/Native/Types/NativeStructs.cs(328,20,328,21) : error CS1056: Unexpected character '$'
http://D/Coding/Process.NET/src/Process.NET/Native/Types/NativeStructs.cs(679,20,679,21) : error CS1056: Unexpected character '$'
http://D/Coding/Process.NET/src/Process.NET/Native/Types/NativeStructs.cs(370,25,370,27) : error CS1002: ; expected
http://D/Coding/Process.NET/src/Process.NET/Native/Types/NativeStructs.cs(370,70,370,71) : error CS1519: Invalid token ';' in class, struct, or interface member declaration
http://D/Coding/Process.NET/src/Process.NET/Utilities/MemoryHelper.cs(40,38,40,39) : error CS1056: Unexpected character '$'
http://D/Coding/Process.NET/src/Process.NET/Utilities/MemoryHelper.cs(54,42,54,43) : error CS1056: Unexpected character '$'
http://D/Coding/Process.NET/src/Process.NET/Utilities/MemoryHelper.cs(71,42,71,43) : error CS1056: Unexpected character '$'
http://D/Coding/Process.NET/src/Process.NET/Utilities/MemoryHelper.cs(96,44,96,45) : error CS1056: Unexpected character '$'
http://D/Coding/Process.NET/src/Process.NET/Utilities/MemoryHelper.cs(115,38,115,39) : error CS1056: Unexpected character '$'
http://D/Coding/Process.NET/src/Process.NET/Utilities/MemoryHelper.cs(140,38,140,39) : error CS1056: Unexpected character '$'
http://D/Coding/Process.NET/src/Process.NET/Utilities/MemoryHelper.cs(171,17,171,18) : error CS1056: Unexpected character '$'
http://D/Coding/Process.NET/src/Process.NET/Utilities/MemoryHelper.cs(195,38,195,39) : error CS1056: Unexpected character '$'
http://D/Coding/Process.NET/src/Process.NET/Utilities/MemoryHelper.cs(264,38,264,39) : error CS1056: Unexpected character '$'
http://D/Coding/Process.NET/src/Process.NET/Utilities/ModuleHelper.cs(32,21,32,22) : error CS1056: Unexpected character '$'
http://D/Coding/Process.NET/src/Process.NET/Utilities/ModuleHelper.cs(42,38,42,39) : error CS1056: Unexpected character '$'

There's about 100+ errors. Project builds fine on 2015. Haven't tried 2017.

**Comment by gir489** [comment]
I found a solution. Since most of these syntax errors are caused by the new C# 6.0, the project should include the latest Microsoft Compilers NuGet project.

https://www.nuget.org/packages/Microsoft.Net.Compilers/1.3.2

**Comment by lolp1** [comment]
Any reason you are not using latest VS? https://www.visualstudio.com/vs/visual-studio-2017-rc/

**Comment by gir489** [comment]
I have a license for 2013.

**Comment by lolp1** [comment]
There is no need for a license - the community version is fully featured and free.

**Comment by gir489** [comment]
Oh wow. They finally figured out charging for a thing most people get for free was stupid? Must've been during the same time Windows also became free. But free things are usually totally free. Microsoft probably collects data you do from Visual Studio (And windows) and sells it. Nothing is ever truly free.

**Comment by lolp1** [comment]
Visual studio community has been totally free since I began programming, visual studio 15 was the current version at that time. You've always been able to turn off visual studios telemetry reporting. They benefit from making community free - more people use their software, supported languages, etc. 

Which leads to business having more motivation to use their platform. They make money from corporations who have to register licenses to use pro/enterprise.

Windows (at least 10) is not free nor has it ever been. Free upgrade from windows 7 is about all they offered, and again that is because they want to get as many people on their platform as possible to make companies have reasons to choose their tech stack.

**Comment by gir489** [comment]
I've been using the Visual series since Visual Studio 6. It just became a norm to have to "pay" for software, despite free software being better.

Like I said, [Nothing is ever free](https://www.infoq.com/news/2016/06/visual-cpp-telemetry)...

I will stay with Visual Studio 2013, because it's the last version before Microsoft started to move towards this "[WE'RE TOTALLY FRIENDS WITH THE OPEN SOURCE COMMUNITY GUYS!](http://i.imgur.com/VAeA885.jpg)" However, as a gesture of friendliness, I did install 2017 to make sure it works...

**Comment by lolp1** [comment]
Sorry to report this project will officially only support the latest visual studio versions.
